### ISSUE TITLE
Can't upload file to Discord

### ISSUE THREAD

**Issue by VoChiDanh** [tsickert/discord-webhook#12]
Link webhook: https://discord.com/api/webhooks/953638985920553000/DMT3wtcH6ZNIr3t8SoLuKqGPMKjwHWgK5ZNW89dDH2wwf9NJcJzyp2wF21l8BhFGq-Al/github

Error

>{'content': 'v2.0 - Fix build again', 'username': 'bCore', 'avatar_url': '[https://github.com/D-x-Z.png'}](https://github.com/D-x-Z.png'%7D)
Traceback (most recent call last):
File "/webhook.py", line 187, in
execute_webhook(payload, args['filename'])
File "/webhook.py", line 1[32](https://github.com/D-x-Z/bCore/runs/5570813619?check_suite_focus=true#step:8:32), in execute_webhook
response = requests.post(args['webhook'], data=payload, files={'upload_file': open(filename, 'rb')})
File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
return request('post', url, data=data, json=json, **kwargs)
File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
prep = self.prepare_request(req)
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 452, in prepare_request
p.prepare(
File "/usr/lib/python3/dist-packages/requests/models.py", line [31](https://github.com/D-x-Z/bCore/runs/5570813619?check_suite_focus=true#step:8:31)3, in prepare
self.prepare_url(url, params)
File "/usr/lib/python3/dist-packages/requests/models.py", line [38](https://github.com/D-x-Z/bCore/runs/5570813619?check_suite_focus=true#step:8:38)7, in prepare_url
raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

You can see the repository here https://github.com/D-x-Z/bCore

**Comment by VoChiDanh** [comment]
Error
> {'content': 'v2.0 - Fix build again', 'username': 'bCore', 'avatar_url': 'https://github.com/D-x-Z.png'}
Traceback (most recent call last):
  File "/webhook.py", line 187, in <module>
    execute_webhook(payload, args['filename'])
  File "/webhook.py", line 1[32](https://github.com/D-x-Z/bCore/runs/5570813619?check_suite_focus=true#step:8:32), in execute_webhook
    response = requests.post(args['webhook'], data=payload, files={'upload_file': open(filename, 'rb')})
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line [31](https://github.com/D-x-Z/bCore/runs/5570813619?check_suite_focus=true#step:8:31)3, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line [38](https://github.com/D-x-Z/bCore/runs/5570813619?check_suite_focus=true#step:8:38)7, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

You can see the repository here https://github.com/D-x-Z/bCore
